# Generated by Django 4.0.3 on 2022-09-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='first_interview',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='second_interview',
            field=models.DateField(default=None, null=True),
        ),
    ]
